#!/bin/bash

if [ "x$IN_DOCKER" = "x1" ]; then
  exec "$@"
fi

root=$(cd $(dirname $0)/..; pwd -P)

xtra=
if [ -n "$PORT" ]; then
  if [ $(uname -s) = Darwin ]; then
    xtra="-p 127.0.0.1:3899:3899 -e PORT=$PORT"
  else
    xtra="--net host -e PORT=$PORT"
  fi
fi

mkdir -p ${root}/dockerhome

exec docker run -it --rm \
  -u $(id -u):$(id -g) \
  -v ${root}:${root} \
  -w $(pwd -P) \
  -e IN_DOCKER=1 $xtra \
  -e HOME=${root}/dockerhome \
  node:14.3.0 "$@"
