#!/bin/bash

set -e
set -o nounset

root=$(cd $(dirname $0)/..; pwd -P)
confdir=${root}/config
conffile=${confdir}/nginx.conf
conflink=/etc/nginx/sites-enabled/school-days

mkdir -p ${confdir}
cat <<NGINX >${conffile}
upstream school-days {
  server 127.0.0.1:3899;
}

server {
  listen 80;
  server_name school-days.localhost;
  root ${root};
}

server {
  listen 80;
  server_name school-days-react.localhost;
  root ${root}/r/public;
  location / {
    proxy_pass http://school-days;
  }
}
NGINX

sudo rm -f ${conflink}
sudo ln -s ${conffile} ${conflink}
sudo systemctl reload nginx

